buildscript {
    repositories {
        maven { url = 'https://files.minecraftforge.net/maven' }
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
    }
}
apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'maven-publish'

version = '0.3.2-1.19.2'
group = 'co.uk.mrpineapple'
archivesBaseName = 'toyguns'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)


minecraft {
    mappings channel: 'official', version: '1.19.2'

    runs {
        client {
            workingDirectory project.file('run')
			property "mixin.env.disableRefMap", "true"
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'

            mods {
                toyguns {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'

            mods {
                toyguns {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
            args '--mod', 'toyguns', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')

            mods {
                toyguns {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
	maven { url = "https://www.cursemaven.com" }
    maven {
        name "Progwml6 maven"
        url "https://dvs1.progwml6.com/files/maven/"
    }
    maven {
        name "ModMaven"
        url "https://modmaven.k-4u.nl"
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.19.2-43.4.0'
    implementation fg.deobf('curse.maven:framework-549225:5692394')
    implementation fg.deobf('curse.maven:controllable-317269:4445137')
    implementation fg.deobf('curse.maven:mrcrayfishs-gun-mod-289479:4718583')
    implementation fg.deobf('curse.maven:configured-457570:4462837')
    implementation fg.deobf('curse.maven:catalogue-459701:4171024')
}

jar {
    manifest {
        attributes([
            "Specification-Title": "Toy Guns Addon",
            "Specification-Vendor": "Mr Pineapple",
            "Specification-Version": "1",
            "Implementation-Title": "Mr Pineapples Toy Guns Addon",
            "Implementation-Version": project.version,
            "Implementation-Vendor" :"Mr. Pineapple",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
		])
    }
}
