#Stuff to load
modLoader="javafml"
loaderVersion="[42,)"
license="GPL3"
issueTrackerURL="https://github.com/Mr-Pineapple/MrPineapplesToyGuns/issues"

#Our Mod Info
[[mods]]
modId="toyguns"
version="0.2"
displayName="Mr Pineapple's Toy Gun Mod Addon"
updateJSONURL="https://raw.githubusercontent.com/Mr-Pineapple/ModUpdateJSON/master/toyguns/update.json"
displayURL="https://mr-pineapple.co.uk/"
authors="Mr. Pineapple"
credits="MrCrayfish"
description='Mr. Pineapples Toy Gun Addon introduces toy guns to MrCrayfishs Gun Mod'

[[dependencies.toyguns]]
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.toyguns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.toyguns]]
    modId="cgm"
    mandatory=true
    versionRange="[1.2.8)"
    ordering="NONE"
    side="BOTH"
[[dependencies.toyguns]]
    modId="framework"
    mandatory=true
    versionRange="[0.3.2,)"
    ordering="NONE"
    side="BOTH"

[modproperties.toyguns]
    catalogueItemIcon="minecraft:stripped_birch_wood"
    configuredBackground="minecraft:textures/block/stripped_birch_log.png"