#Stuff to load
modLoader="javafml"
loaderVersion="[32,)"
license="GPL3"

#Our Mod Info
[[mods]]
modId="toyguns"
version="0.2"
displayName="Mr Pineapple's Toy Gun Mod Addon"
updateJSONURL="https://raw.githubusercontent.com/Mr-Pineapple/ModUpdateJSON/master/toyguns/update.json"
displayURL="https://mr-pineapple.co.uk/"
authors="Mr. Pineapple"
credits="MrCrayfish"
description='Mr. Pineapples Toy Gun Addon introduces toy guns to MrCrayfishs Gun Mod'

#Dependencies are an integral part of this
#We need to add forge and minecraft to run the game
#However, we also need to require the Gun mod, as well as Obfuscate
#We need the Gun Mod so we can register guns and other related stuff
#We need Obfuscate because it is a required dependency of the Gun Mod

#The fields marked with mandatory need to be present when loading the game
#They are present in the IDE as we added them to our build.gradle file
#Something like controllable isn't needed, however, we still add it as the mod supports that and adds features around it.
[[dependencies.toyguns]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.toyguns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.toyguns]]
    modId="cgm"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.toyguns]]
    modId="obfuscate"
    mandatory=true
    versionRange="[0.6.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.toyguns]]
    modId="controllable"
    mandatory=false
    versionRange="[0.10.3,)"
    ordering="AFTER"
    side="CLIENT"